# -*- coding: utf-8 -*-
# Deployment settings for c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Program Files/Marmalade 7.2/s3e/makefile_builder/mkb.py', 'd:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/Time4Life.mkb', '--deploy-only', '--hub-data', 'D:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/project_Time4Life/mkb-web.txt', '--buildenv=WEB', '--use-prebuilt']
mkb = 'd:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/Time4Life.mkb'
mkf = ['c:\\program files\\marmalade 7.2\\web\\wmapplication\\wmapplication_prebuilt.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/webassets', 'webassets', 0),
    ('d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/iwaudiocapture', 'iwaudiocapture', 0),
]

assets['including_iwui_style'] = [
    ('d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/webassets', 'webassets', 0),
    ('d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/iwaudiocapture', 'iwaudiocapture', 0),
    ('d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/iwui_style', 'iwui_style', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Time4Life'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Time4Life'
    long_caption = 'Time4Life'
    version = [0, 0, 1]
    config = ['d:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data/app.icf']
    data_dir = 'd:/UserData/Projects/5HourApps/Time4Life/Marmalade/Time4Life/data'
    iphone_link_lib = ['s3eWebView', 's3eDialog', 's3eNUI ', 's3eOverlay']
    osx_ext_dll = ['c:/program files/marmalade 7.2/extensions/s3ewebview/lib/osx/libs3eWebView.dylib', 'c:/program files/marmalade 7.2/extensions/s3edialog/lib/osx/libs3eDialog.dylib', 'c:/program files/marmalade 7.2/web/wmapplication/extensions/s3eoverlay/lib/osx/libs3eOverlay.dylib']
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/program files/marmalade 7.2/extensions/s3ewebview/lib/win32/s3eWebView.dll', 'c:/program files/marmalade 7.2/extensions/s3edialog/lib/win32/s3eDialog.dll', 'c:/program files/marmalade 7.2/web/wmapplication/extensions/s3eoverlay/lib/win32/s3eOverlay.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['c:/program files/marmalade 7.2/extensions/s3ewebview/lib/iphone', 'c:/program files/marmalade 7.2/extensions/s3edialog/lib/iphone', 'c:/program files/marmalade 7.2/extensions/s3enui/lib/iphone', 'c:/program files/marmalade 7.2/web/wmapplication/extensions/s3eoverlay/lib/iphone']
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = ['c:/program files/marmalade 7.2/extensions/s3ewebview/lib/android/s3eWebView.jar', 'c:/program files/marmalade 7.2/extensions/s3edialog/lib/android/s3eDialog.jar', 'c:/program files/marmalade 7.2/extensions/s3enui/lib/android/s3eNUI.jar', 'c:/program files/marmalade 7.2/extensions/s3eaudiocapture/lib/android/s3eAudioCapture.jar', 'c:/program files/marmalade 7.2/web/wmapplication/extensions/s3eoverlay/lib/android/s3eOverlay.jar']
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = []
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = ['c:/program files/marmalade 7.2/extensions/s3ewebview/lib/android/libs3eWebView.so', 'c:/program files/marmalade 7.2/extensions/s3edialog/lib/android/libs3eDialog.so', 'c:/program files/marmalade 7.2/extensions/s3enui/lib/android/libs3eNUI.so', 'c:/program files/marmalade 7.2/extensions/s3eaudiocapture/lib/android/libs3eAudioCapture.so', 'c:/program files/marmalade 7.2/web/wmapplication/extensions/s3eoverlay/lib/android/libs3eOverlay.so']
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.s86',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.s3e',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.so',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.so',
                 },
         'arm' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.s3e',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication_d.s86',
                   'release' : r'c:\program files\marmalade 7.2\web\wmApplication\target\wmApplication.s86',
                 },
        }
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()

######### Configuration: Windows

c = DeployConfig()
config['Windows'] = c
c.os = ['win32']
c.arch = ['x86']
c.target_folder = 'Windows'
c.assets = assets['including_iwui_style']

######### Configuration: Mac OS X

c = DeployConfig()
config['Mac OS X'] = c
c.os = ['osx']
c.arch = ['x86']
c.target_folder = 'Mac OS X'
c.assets = assets['including_iwui_style']
